In [3]:
import torch
from torch import nn
from torch.nn import functional as F

net = nn.Sequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))

X = torch.rand(2, 20)
net(X)

tensor([[ 0.2285,  0.2613,  0.1361,  0.0014,  0.2131,  0.1412,  0.0820, -0.0431,
         -0.0366, -0.1704],
        [ 0.1821,  0.2234,  0.0999,  0.0304,  0.2993,  0.1595,  0.1701,  0.0369,
          0.0166, -0.1487]], grad_fn=<AddmmBackward0>)

In [5]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.out = nn.Linear(256, 10)
    def forward(self, X):
        return self.out(F.relu(self.hidden(X)))

In [7]:
net = MLP()
net(X)

tensor([[-0.1901, -0.0443,  0.0327, -0.1635, -0.1579, -0.1910, -0.0397,  0.1250,
         -0.2797, -0.0546],
        [-0.2141,  0.0085, -0.0784, -0.0167, -0.1103, -0.4056, -0.0210,  0.1975,
         -0.1185,  0.0235]], grad_fn=<AddmmBackward0>)

In [9]:
class MySequential(nn.Module):
    def __init__(self, *args):
        super().__init__()
        for idx, module in enumerate(args):
            self._modules[str(idx)] = module
    def forward(self, X):
        for block in self._modules.values():
            X = block(X)
        return X

In [10]:
net = MySequential(nn.Linear(20, 256), nn.ReLU(), nn.Linear(256, 10))
net(X)

tensor([[-0.1140,  0.0209, -0.0753,  0.2583, -0.0746,  0.2484,  0.0423, -0.0547,
          0.1007,  0.0651],
        [ 0.1085, -0.1290, -0.0640,  0.0519,  0.0498,  0.2200, -0.0075,  0.0130,
          0.0795, -0.1061]], grad_fn=<AddmmBackward0>)