In [3]:
%matplotlib inline
import random
import torch
from d2l import torch as d2l

In [4]:
def synthetic_data(w, b, num_examples):
#     生成y=Xw+b+epsilon
#      X.size = tensor(样本数，特征长度)
    X = torch.normal(0, 1, (num_examples, len(w))) 
    y = torch.matmul(X, w) + b
    y += torch.normal(0, 0.01, y.shape)
    return X, y.reshape((-1, 1))

In [8]:
param_w = torch.tensor([2, -3.4])
param_b = 4.2
features, labels = synthetic_data(param_w, param_b, 1000)
print(f'特征格式为', features.shape, f'标签格式为', labels.shape)

特征格式为 torch.Size([1000, 2]) 标签格式为 torch.Size([1000, 1])


In [9]:
def data_iter(batch_size, features, labels):
    num_examples = len(features)
    indices = list(range(num_examples))
    random.shuffle(indices)
    for i in range(0, num_examples, batch_size):
        batch_indices = torch.tensor(indices[i: min(i+batch_size, num_examples)])
        yield features[batch_indices], labels[batch_indices]

In [14]:
batch_size = 10
for X, y in data_iter(batch_size, features, labels):
    print(X, '\n', y)

tensor([[ 0.7203, -1.0861],
        [-1.9780, -0.2384],
        [ 0.2660,  0.5243],
        [ 0.4583,  1.5608],
        [ 0.2052,  1.3559],
        [ 0.5596,  0.0244],
        [ 0.5036, -0.3588],
        [ 0.5095,  0.2490],
        [-0.0338, -0.3790],
        [ 0.4996, -1.1469]]) 
 tensor([[ 9.3266],
        [ 1.0577],
        [ 2.9310],
        [-0.1800],
        [-0.0152],
        [ 5.2404],
        [ 6.4129],
        [ 4.3748],
        [ 5.4031],
        [ 9.0983]])
tensor([[-2.4218,  0.9820],
        [-1.0717,  0.4548],
        [ 2.7195, -0.6116],
        [-0.6259,  1.1292],
        [ 0.3198, -0.2314],
        [-0.5909, -0.9911],
        [-0.6038, -0.4146],
        [-0.5803,  1.2066],
        [ 0.6646, -0.2466],
        [-1.0593, -1.2357]]) 
 tensor([[-3.9830],
        [ 0.5101],
        [11.7239],
        [-0.8824],
        [ 5.6237],
        [ 6.3789],
        [ 4.4102],
        [-1.0647],
        [ 6.3716],
        [ 6.3012]])
tensor([[ 1.1662,  3.5013],
        [-0.3442,  1.553